server {
    listen 9222;

    location / {
        proxy_pass http://chrome:9222;
        proxy_set_header Host localhost:9222;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 3600s;

        # Rewrite ws://localhost trong JSON response → chrome-proxy
        sub_filter '"ws://localhost:9222/' '"ws://chrome-proxy:9222/';
        sub_filter_once off;
        sub_filter_types application/json;
    }
}